/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'slawek' at '6/9/17 11:11 PM' with Gradle 3.2.1
 *
 * @author slawek, @date 6/9/17 11:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
